import Link from "next/link";
import Image from "next/image";
import type { Metadata } from "next";
import { validateAuthToken } from "@/lib/auth/tokens";
import { PASSWORD_MIN_LENGTH } from "@/lib/auth/constants";
import SetupPasswordForm from "@/components/SetupPasswordForm";

export const metadata: Metadata = { title: "Set Up Your Account — SG Maid" };

/**
 * Employer account-setup page — Phase 2. Reached via the one-time
 * invitation link generated by scripts/create-dev-employer-invite.ts (a
 * real invite/email flow is future work — see that script's header
 * comment). Mirrors the /login page's visual layout rather than
 * introducing new design language.
 *
 * The token is checked here (without consuming it) purely to decide
 * whether to render the form or a generic "link no longer valid"
 * message — the Server Action in actions.ts re-validates and actually
 * consumes it on submit, which is the real security boundary.
 */
export default async function SetupPasswordPage({
  searchParams,
}: {
  searchParams: Promise<{ token?: string }>;
}) {
  const { token } = await searchParams;
  const validation = token ? await validateAuthToken(token, "ACCOUNT_SETUP") : null;
  const linkIsUsable = Boolean(validation?.ok);

  return (
    <main
      style={{
        minHeight: "100dvh",
        display: "grid",
        placeItems: "center",
        padding: "48px 24px",
        position: "relative",
        overflow: "hidden",
        background: "var(--cream)",
      }}
    >
      <svg
        className="rings"
        viewBox="0 0 200 200"
        aria-hidden="true"
        style={{ top: -140, right: -140, width: 420, height: 420, color: "var(--purple)", opacity: 0.1 }}
      >
        <circle cx="100" cy="100" r="26" stroke="currentColor" />
        <circle cx="100" cy="100" r="46" stroke="currentColor" />
        <circle cx="100" cy="100" r="66" stroke="currentColor" />
        <circle cx="100" cy="100" r="86" stroke="currentColor" />
      </svg>

      <div className="card" style={{ width: "100%", maxWidth: 420, position: "relative", zIndex: 1 }}>
        <Link href="/" style={{ display: "inline-flex", marginBottom: 24 }} aria-label="SG Maid home">
          <Image src="/sgmaid-logo-colored.png" alt="SG Maid" width={160} height={68} style={{ height: 36, width: "auto" }} />
        </Link>
        <span className="eyebrow">Employer Portal</span>

        {linkIsUsable && token ? (
          <>
            <h1 style={{ fontSize: "1.7rem", marginBottom: 8 }}>Set up your account</h1>
            <p style={{ fontSize: ".92rem", color: "var(--ink-70)", marginBottom: 24 }}>
              Choose a password to activate your SG Maid employer account.
            </p>
            <SetupPasswordForm token={token} minLength={PASSWORD_MIN_LENGTH} />
          </>
        ) : (
          <>
            <h1 style={{ fontSize: "1.7rem", marginBottom: 8 }}>This link is no longer valid</h1>
            <p className="form-notice form-notice--error">
              This account setup link is invalid, expired, or has already been used.
            </p>
            <p style={{ fontSize: ".92rem", color: "var(--ink-70)" }}>
              Please <Link href="/contact" style={{ color: "var(--purple)", fontWeight: 600 }}>contact SG Maid</Link> to
              request a new invitation.
            </p>
          </>
        )}

        <p className="form-alt">
          <Link href="/">← Back to the public site</Link>
        </p>
      </div>
    </main>
  );
}
